//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace csharp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("csharp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{{},{{{&lt;,u,!{}!&gt;,&lt;&apos;e&lt;&apos;,&gt;,&lt;{!!o!&gt;!&gt;!,&lt;&quot;!!oa!&gt;o!!!&gt;}!!!&gt;!!!&gt;,!!&gt;},{&lt;!&gt;,&lt;i&gt;,&lt;,!!u!!!!!!!&gt;a&quot;o!&gt;},&lt;eu!!!&gt;!!!&gt;!!!!!&gt;!&gt;,&lt;&gt;},{}},{{&lt;!!!&gt;i,a!!oa!!i!&gt;,&lt;!&gt;,&lt;o&gt;,&lt;!!}{!!!!&quot;!!,!!&apos;,!!!&gt;&apos;&gt;},{&lt;&apos;{}&quot;&apos;!!&quot;&gt;},{}},{{&lt;!!u&gt;,{&lt;&gt;}},{{&lt;o{e&lt;!&gt;},&lt;o!!}!&gt;iu&lt;e!&gt;,&lt;eo&gt;,{&lt;,!!!!!&gt;!i!!!&gt;}a&apos;o,e&lt;!!o!&gt;},&lt;,!&gt;,&lt;&gt;}}},{{},{&lt;&gt;,{&lt;!&gt;,&lt;}!&quot;!!o&gt;,&lt;aoo,&gt;}}}},{{{{&lt;,&quot;&quot;,&gt;,&lt;i&gt;},{{&lt;!!,&lt;&apos;!&gt;,&lt;u{o!!!&gt;!&gt;e!&lt;{oe}!!i&apos;&gt;}}},{{{{&lt;{o&apos;!&gt;!&gt;},&lt;&gt;}},{{&lt;&lt;!&gt;},&lt;&apos;!!!&gt;!,!&gt;!!!&gt;!!u!&gt;!!}!!&lt;!&gt;!&gt;},&lt;!!!&gt;,,a&gt;},&lt;!&gt;,&lt;!&gt;,&lt;i!!!&gt;}!&gt;},&lt;&quot;!&gt;,&lt;&lt;{o}&quot;&apos;!&gt;},&lt;!{&gt;},{{&lt;au!!!&gt;!!!!}!&apos;eo!!!{!&gt;u!!!!!!!,!!!&gt;&apos;u! [rest of string was truncated]&....
        /// </summary>
        internal static string Day9 {
            get {
                return ResourceManager.GetString("Day9", resourceCulture);
            }
        }
    }
}
